### ISSUE TITLE
Issues using CLI

### ISSUE THREAD

**Issue by ablazier-rl** [wdullaer/raml2slate#2]
Hey,

Thanks so much for putting this together! I'm having some difficulties working with the command line interface, though. Here's what I'm seeing:

```
~/g/u/data » raml2slate -i minimal.raml -o slate
Something went wrong rendering the documentation
Error: template not found: /usr/local/lib/node_modules/raml2slate/templates/index.nunjucks
    at createTemplate (/usr/local/lib/node_modules/raml2slate/node_modules/nunjucks/src/environment.js:206:31)
    at next (/usr/local/lib/node_modules/raml2slate/node_modules/nunjucks/src/lib.js:210:13)
    at handle (/usr/local/lib/node_modules/raml2slate/node_modules/nunjucks/src/environment.js:252:25)
    at /usr/local/lib/node_modules/raml2slate/node_modules/nunjucks/src/environment.js:263:21
    at next (/usr/local/lib/node_modules/raml2slate/node_modules/nunjucks/src/lib.js:207:13)
    at Object.exports.asyncIter (/usr/local/lib/node_modules/raml2slate/node_modules/nunjucks/src/lib.js:214:5)
    at Obj.extend.getTemplate (/usr/local/lib/node_modules/raml2slate/node_modules/nunjucks/src/environment.js:242:17)
    at Obj.extend.render (/usr/local/lib/node_modules/raml2slate/node_modules/nunjucks/src/environment.js:303:14)
    at Promise (/usr/local/lib/node_modules/raml2slate/node_modules/raml2md/index.js:25:26)
    at raml2obj.parse.then (/usr/local/lib/node_modules/raml2slate/node_modules/raml2md/index.js:24:12)
    at _fulfilled (/usr/local/lib/node_modules/raml2slate/node_modules/q/q.js:798:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/raml2slate/node_modules/q/q.js:827:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/raml2slate/node_modules/q/q.js:760:13)
    at /usr/local/lib/node_modules/raml2slate/node_modules/q/q.js:574:44
    at flush (/usr/local/lib/node_modules/raml2slate/node_modules/q/q.js:108:17)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
```

I'm quite sure that the file exists, though:
```
~/g/u/data » cat minimal.raml
#%RAML 0.8
title: Rocketlawyer User REST API
version: v1
protocols: [ HTTPS ]
baseUri: http://rocketlawyer.com/users/v1/
mediaType: application/json
/:
```

```
~/g/u/data » file /usr/local/lib/node_modules/raml2slate/templates/index.nunjucks
/usr/local/lib/node_modules/raml2slate/templates/index.nunjucks: ASCII text
```

I think this may be a bug specific to the CLI. Any assistance is appreciated!

**Comment by wdullaer** [comment]
Let me take a look at this.
The library can still use some improvements. I basically worked on it until it could satisfy the requirements I had at work.

**Comment by wdullaer** [comment]
I can't reproduce this.
Took a fresh global install, ran a test RAML through it and everything worked just fine.
Maybe the install got borked?

**Comment by ablazier-rl** [comment]
I've attempted fresh installs without any success getting this to work. However, when attempting a fresh install on a different machine everything seems to be working fine. It seems there's something specific to my primary device that's causing this issue. I'll update if I figure out exactly what it is that's causing the issue.

Thanks so much for taking the time to look at this, and thanks again for the nice lib.

**Comment by wdullaer** [comment]
No worries.
I found another bug when investigating this (an underlying dependency doesn't seem to cope with having a space in the path to the raml file very well).

When you have some more information, let me know.

**Comment by sichvoge** [comment]
hi, facing the same issue and created a separate issue #4. Will close the other one since this should be fine. @ablazier-rl could you reproduce it on your other machine?

**Comment by wdullaer** [comment]
Can you maybe list what version of npm and node you are using?
Also: which OS? Are you running it in a subpath with spaces?

I can't reproduce the issue, so whatever information you have will be useful.
Can you maybe also double check that the template content is not corrupted?

**Comment by sichvoge** [comment]
NPM version: 3.5.0
Node version: v5.1.0
OS: Mac OS

No paths with spaces :)

**Comment by tonyhoo** [comment]
I was able to repro the same issue on MacOS and Redhat Linux
OS: Mac OS
NPM version: 4.0.5
Node version: v7.4.0

OS: AmazonLinux (EC2)
NPM version: 3.4.0
Node version: v4.2.2

**Comment by wdullaer** [comment]
@tonyhoo I managed to reproduce this on an ec2 amazon linux instance.
In my case it seems to be linked to global install. (`npm install -g`)
If you install the library locally, it works just fine, so you could try that as a temporary workaround until I managed to locate the root cause

(I'm currently leaning towards a permission problem, place your bets ... )

**Comment by tonyhoo** [comment]
@wdullaer Thanks for your timely reply. I tried local install as well without any luck. Could you share your brief steps for local install as well?

**Comment by wdullaer** [comment]
```bash
mkdir raml2slate
cd raml2slate
npm install raml2slate
./node_modules/.bin/raml2slate -i api.raml -o /my/output/folder
```

I have found and fixed the issue in the meantime. There was one bug in my code, and one bug in a dependency which prevented the library to be used when globally installed. I've opened a PR on the dependency, if they merge and release it quickly I can release a new version of this. Otherwise I'll have to bring that code into the library.

**Comment by sichvoge** [comment]
What's the dependency that fails?

**Comment by wdullaer** [comment]
metalsmith-stylus has a faulty function to turn relative paths into absolute paths, which fails if an absolute path is not a subpath of the current working directory.
I've fixed it and opened a PR.
They reacted quite quickly to a PR in the past, so I have good hopes.
If they don't, I'll pull the relevant code into this module (I don't want to release something to npm that pulls a dependency from git)

**Comment by tonyhoo** [comment]
@wdullaer  I have found the same issue as well. For the temporary workaround, I just used absolute path which is not under the current working directory. Thanks for the quick turnaround

**Comment by wdullaer** [comment]
I've pushed a fix to master (I had to move some dependencies into the codebase so I could fix them)

Can any of you globally install the master branch and confirm that the issue is resolved (My test cases are passing, but I want to be sure)
```sh
npm install -g git+https://github.com/wdullaer/raml2slate#master
```

**Comment by sichvoge** [comment]
I do get this now:

```
module.js:340
    throw err;
    ^

Error: Cannot find module '../plugins/metalsmith-assets'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/christianmule/.node/lib/node_modules/raml2slate/lib/index.js:12:16)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/christianmule/.node/lib/node_modules/raml2slate/lib/cli.js:7:29)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
```

**Comment by sichvoge** [comment]
Looking at the path and the directory there is no `raml2slate/plugins` folder.

**Comment by wdullaer** [comment]
Good catch. I didn't add `plugins` to the list of required folders in `package.json`
Should be fixed now

**Comment by sichvoge** [comment]
Works like a charm now. Thanks!

**Comment by wdullaer** [comment]
available as v0.0.7 now

**Comment by ramizmoh** [comment]
Hi 

This still seems to be an issue when installed on the Windows 10 OS.

Attempts to run via the CLI when installed locally or globally, returns the same result.

`C:\raml2slate\node_modules\.bin>raml2slate -i C:\Users\userid\Desktop\User\raml_files\User.raml -o C:\Users\userid\Desktop\User\raml_files\slate_docs
Something went wrong rendering the documentation
{ Error: css\style.styl:2:9
   1| @import '_normalize.css'
   2| @import '_variables'
--------------^
   3| @import '_icon_font'
   4|
   5|

failed to locate @import file _variables.styl

    at Evaluator.visitImport (C:\raml2slate\node_modules\stylus\lib\visitor\evaluator.js:915:21)
    at Evaluator.Visitor.visit (C:\raml2slate\node_modules\stylus\lib\visitor\index.js:28:40)
    at Evaluator.visit (C:\raml2slate\node_modules\stylus\lib\visitor\evaluator.js:160:18)
    at Evaluator.visitRoot (C:\raml2slate\node_modules\stylus\lib\visitor\evaluator.js:707:27)
    at Evaluator.Visitor.visit (C:\raml2slate\node_modules\stylus\lib\visitor\index.js:28:40)
    at Evaluator.visit (C:\raml2slate\node_modules\stylus\lib\visitor\evaluator.js:160:18)
    at Evaluator.evaluate (C:\raml2slate\node_modules\stylus\lib\visitor\evaluator.js:247:15)
    at Renderer.render (C:\raml2slate\node_modules\stylus\lib\renderer.js:86:26)
    at C:\raml2slate\node_modules\raml2slate\plugins\metalsmith-stylus.js:40:9
    at Array.forEach (native)
    at Ware.<anonymous> (C:\raml2slate\node_modules\raml2slate\plugins\metalsmith-stylus.js:22:12)
    at Ware.<anonymous> (C:\raml2slate\node_modules\wrap-fn\index.js:45:19)
    at next (C:\raml2slate\node_modules\ware\lib\index.js:85:20)
    at C:\raml2slate\node_modules\wrap-fn\index.js:121:18
    at Promise.all.then (C:\raml2slate\node_modules\raml2slate\plugins\metalsmith-assets.js:48:11)
  lineno: 2,
  column: 9,
  filename: 'css\\style.styl',
  stylusStack: '' }`

Your assistance is appreciated.

**Comment by wdullaer** [comment]
Can you double check for me that you are using the latest version?

Also: I do not test on Windows and generally assume unix like systems for all my npm scripts.
I'm porting this to be a theme for raml2html, which should have better Windows compatibility (hopefully)

**Comment by ramizmoh** [comment]
Hi

Thank you for the prompt response.

I can confirm that I am using the latest version of the plugin.

My attempts at reinstalling and starting again have proven to be
unsuccessful.

Based on the CLI code samples you have provided,  I anticipated that it was
developed for Linux based OS.

Regards

**Comment by ramizmoh** [comment]
Hi

I managed to resolve this issue by running your scripts using the Bash on Ubuntu for Windows software.

Thank you for your time.
